<?php
declare(strict_types=1);

namespace SlaunchX\Plutus\Tests;

use SlaunchX\Plutus\Exception\ConfigurationException;
use SlaunchX\Plutus\Exception\ResponseSignatureException;
use SlaunchX\Plutus\Http\RawResponse;
use SlaunchX\Plutus\PlutusClient;
use SlaunchX\Plutus\ProtocolProfile;
use SlaunchX\Plutus\RequestSigner;

final class ProductRequestIdCompatibilityTest extends VectorTestCase
{
    private function response(string $id, ?string $responseId = null, bool $tamperBody = false): RawResponse
    {
        $body = '{"success":true,"code":"2000","data":[]}';
        $time = '1788836400000';
        $canonical = implode("\n", [$id, '200', 'application/json', $time, hash('sha256', $body)]);
        openssl_sign($canonical, $signature, self::privateKeyPem('platform_auth'), OPENSSL_ALGO_SHA256);
        $headers = [
            'Content-Type' => 'application/json',
            'X-Response-Timestamp' => $time,
            'X-Response-Signature-Algorithm' => 'RSA-SHA256',
            'X-Response-Signature' => base64_encode($signature),
        ];
        if ($responseId !== null) {
            $headers['X-Request-Id'] = $responseId;
        }
        return new RawResponse(200, $headers, $body . ($tamperBody ? ' ' : ''));
    }

    public function testAutoGeneratedIdsAllowMissingResponseHeaderAndAreUnique(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn(array $sent) => $this->response($sent['headers']['X-Request-Id'] ?? 'server-generated'));
        $client = new PlutusClient($config, $transport);
        self::assertTrue($client->get('/card-products/cards/page')->signatureVerified);
        self::assertTrue($client->post('/card-products/groups/list', ['json' => ['isActive' => true]])->signatureVerified);
        $first = $transport->sent[0]['headers']['X-Request-Id'];
        self::assertMatchesRegularExpression('/^req_[0-9a-f]{32}$/D', $first);
        self::assertNotSame($first, $transport->sent[1]['headers']['X-Request-Id']);
    }

    public function testExplicitRequestIdCanVerifyMissingResponseHeader(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn() => $this->response('custom-id'));
        $response = (new PlutusClient($config, $transport))->get('/card-products/cards/page', ['requestId' => 'custom-id']);
        self::assertTrue($response->signatureVerified);
        self::assertSame('custom-id', $transport->last()['headers']['X-Request-Id']);
    }

    public function testLowercaseExtraHeaderIsPreservedAndNormalized(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn() => $this->response('custom-id'));
        $response = (new PlutusClient($config, $transport))->get('/card-products/cards/page', ['headers' => ['x-request-id' => ' custom-id ']]);
        self::assertTrue($response->signatureVerified);
        self::assertSame('custom-id', $transport->last()['headers']['X-Request-Id']);
        self::assertArrayNotHasKey('x-request-id', $transport->last()['headers']);
    }

    public function testConflictingCaseInsensitiveRequestIdsAreRejected(): void
    {
        $this->expectException(ConfigurationException::class);
        (new RequestSigner(self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1])))
            ->sign('GET', '/card-products/cards/page', requestId: 'first', extraHeaders: ['x-request-id' => 'second']);
    }

    public function testPresentButIncorrectResponseIdDoesNotFallBack(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn() => $this->response('custom-id', 'wrong-id'));
        $this->expectException(ResponseSignatureException::class);
        (new PlutusClient($config, $transport))->get('/card-products/cards/page', ['requestId' => 'custom-id']);
    }

    public function testMissingResponseHeaderStillRejectsTamperedBody(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn() => $this->response('custom-id', tamperBody: true));
        $this->expectException(ResponseSignatureException::class);
        (new PlutusClient($config, $transport))->get('/card-products/cards/page', ['requestId' => 'custom-id']);
    }

    public function testMissingResponseHeaderRejectsSignatureForAnotherRequest(): void
    {
        $config = self::config(['protocolProfile' => ProtocolProfile::PRODUCT_V1]);
        $transport = new FakeTransport(fn() => $this->response('another-request'));
        $this->expectException(ResponseSignatureException::class);
        (new PlutusClient($config, $transport))->get('/card-products/cards/page', ['requestId' => 'custom-id']);
    }

    public function testDefaultProfileDoesNotAutoGenerateRequestId(): void
    {
        $signed = (new RequestSigner(self::config()))->sign('GET', '/card-products/cards/page');
        self::assertArrayNotHasKey('X-Request-Id', $signed->headers);
    }
}
